Bootstrap: docker
From: ubuntu:22.04

%help
	This is an Apptainer container of Ubuntu 22.04 with TurboVNC and XFCE installed.
	It is intended to be used as a base for other containers that need a VNC server.
	It is designed to be run on the Hyak cluster at the University of Washington with the hyakvnc script.

%setup
	[ -n "${APPTAINER_ROOTFS:-}" ] && ../../bin/write-apptainer-labels.sh > "${APPTAINER_ROOTFS}/.build_labels"

%files
	../../common/configs/ubuntu /opt/setup/configs
	../../common/scripts /opt/setup/scripts

%environment
{
	export LANG=en_US.utf8
	export LC_ALL=en_US.utf8
	export LC_COLLATE=C
	export SHELL="${SHELL:-/bin/bash}"
	export PATH="/opt/local/bin:/opt/TurboVNC/bin:${PATH}"
}

%post
{
	set -e # Exit on error
	set -x # Print commands as they are executed
	export DEBIAN_FRONTEND=noninteractive

	apt-get update -y -qq
	apt-get install -y -qq apt-utils

	# Don't generate these locales"
	mkdir -p /var/lib/locales/supported.d
	for localename in fr de zh-hant ja es it zh-hans pt ru ar; do
		touch "/var/lib/locales/supported.d/${localename}" && chmod a-r "/var/lib/locales/supported.d/${localename}"
	done

	# Generate the locales
	apt-get install -y locales
	localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.utf8

	# Set the locale environment variables permanently:
	export LANG=en_US.utf8 && echo "LANG=\"${LANG}\"" >>/etc/environment
	export LC_ALL=en_US.utf8 && echo "LC_ALL=\"${LC_ALL}\"" >>/etc/environment
	export LC_COLLATE=C && echo "LC_COLLATE=\"${LC_COLLATE}\"" >>/etc/environment

	# Stop apt from installing audio packages (they don't work on VNC):
	apt-mark hold xfce4-pulseaudio-plugin pavucontrol pulseaudio pipewire pipewire-bin pipewire-pulse

	# Install basic packages:
	apt-get install -yq \
		bash-completion \
		bash-doc \
		bc \
		binutils \
		bzip2 \
		ca-certificates \
		curl \
		dash \
		file \
		git \
		less \
		make \
		nano \
		netcat-openbsd \
		openssh-client \
		procps \
		psmisc \
		python3 \
		rsync \
		vim-tiny \
		zip

	# Install XFCE and some apps:
	apt-get install -yq --no-install-recommends \
		at-spi2-core \
		dbus-x11 \
		elementary-xfce-icon-theme \
		fonts-dejavu-core \
		fonts-freefont-ttf \
		fonts-ubuntu \
		greybird-gtk-theme \
		libnotify-bin \
		libxfce4ui-utils \
		mousepad \
		novnc \
		ristretto \
		thunar \
		thunar-archive-plugin \
		thunar-volman \
		x11-utils \
		x11-xserver-utils \
		xauth \
		xclip \
		xdg-user-dirs \
		xdg-utils \
		xfce4-appfinder \
		xfce4-datetime-plugin \
		xfce4-indicator-plugin \
		xfce4-notes-plugin \
		xfce4-notifyd \
		xfce4-panel \
		xfce4-screenshooter \
		xfce4-session \
		xfce4-settings \
		xfce4-taskmanager \
		xfce4-terminal \
		xfce4-whiskermenu-plugin \
		xfconf \
		xfdesktop4 \
		xfonts-base \
		xfwm4 \
		xterm \
		xvfb \
		zip

	# Set xfce4-terminal as default terminal emulator:
	update-alternatives --set x-terminal-emulator /usr/bin/xfce4-terminal.wrapper

	# Install TurboVNC:
	/opt/setup/scripts/install-turbovnc.sh

	# shellcheck disable=SC2016
	echo '$vncUserDir = "$ENV{VNC_USER_DIR}";' >>/etc/turbovncserver.conf
	# Copy configs:
	rsync -avi --no-p --no-g --chmod=ugo=rwX /opt/setup/configs/ /

	# Move hyakvnc-vncserver.sh to /opt/local/bin:
	mkdir -p /opt/local/bin
	mv /opt/setup/scripts/hyakvnc-vncserver.sh /opt/local/bin/hyakvnc-vncserver

	# Erase the setup files:
	rm -rf /opt/setup

	# Clean up packages:
	apt-get clean -y -qq && rm -rf /var/lib/apt/lists/*
}

%runscript
{
	exec hyakvnc-vncserver "$@"
}

%startscript
{
	exec hyakvnc-vncserver "$@"
}
