Bootstrap: docker
From: ubuntu:22.04

%help
This is an Apptainer container of Ubuntu 22.04 with TurboVNC and XFCE installed. It is intended to be used as a base for other containers that need a VNC server. It is designed to be run on the Hyak cluster at the University of Washington with the hyakvnc script.

%arguments
# SETUP_DOWNLOADS_MOUNT [optional] [default: "/opt/.setup-downloads"] The path to the directory where the setup files will be downloaded. This directory should be mounted as a volume in the container.
  SETUP_DOWNLOADS_MOUNT="/opt/.setup-downloads"

%setup
	../../bin/write-apptainer-labels.sh > "${APPTAINER_ROOTFS}/.build_labels"
  [ -n "${SETUP_DOWNLOADS_MOUNT:-}" ] && export SETUP_DOWNLOADS_MOUNT="${SETUP_DOWNLOADS_MOUNT}" && mkdir -p "${APPTAINER_ROOTFS}/${SETUP_DOWNLOADS_MOUNT}"

%labels
	edu.uw.hyakvnc.container.resources.recommends.mem 2G
	edu.uw.hyakvnc.container.resources.requires.mem 2G
	edu.uw.hyakvnc.container.resources.recommends.cpus 1
	edu.uw.hyakvnc.container.resources.requires.cpus 1
	
%files
  ../../common /opt/setup

%post
	set -x
	export DOWNLOAD_DIR="${DOWNLOAD_DIR:-${SETUP_DOWNLOADS_MOUNT:-/opt/.setup-downloads}}" && mkdir -p "${DOWNLOAD_DIR}" && ls -la "${DOWNLOAD_DIR}"

	export LANG=en_US.UTF-8
	export LC_ALL=en_US.UTF-8
	export LC_COLLATE=C

	export DEBIAN_FRONTEND=noninteractive
	apt-get update -y -qq

	# Install base packages:
	/opt/setup/scripts/install-ubuntu22.04-base.sh || { echo "warning: install-ubuntu22.04-base.sh failed!" >&2; exit 1; }

	# Install hyakvnc dependencies and hyakvnc:
	/opt/setup/scripts/install-ubuntu22.04-hyakvnc-vncserver.sh || { echo "warning: install-ubuntu22.04-hyakvnc-vncserver.sh failed!" >&2; exit 1; }

	# Erase the setup files:
	rm -rf /opt/setup

	# Clean up packages:
	apt-get clean -y -qq && apt-get -y autoremove && rm -rf /var/lib/apt/lists/*


%runscript
  hyakvnc-vncserver "$@"

%startscript
  hyakvnc-vncserver "$@"
