Bootstrap: {{BOOTSTRAP_SOURCE}}
From: {{BOOTSTRAP_FROM_REPO}}/{{BOOTSTRAP_FROM_IMAGE}}{{BOOTSTRAP_FROM_SUFFIX}}

%arguments
	BOOTSTRAP_SOURCE=localimage
	BOOTSTRAP_FROM_REPO=../../sif
	BOOTSTRAP_FROM_IMAGE=hyakvnc-freesurfer-ubuntu22.04
	BOOTSTRAP_FROM_SUFFIX=.sif
	SETUP_DOWNLOADS_DIR=../../.setup-downloads
  MCR_VERSION=R2014b
  APT_CLEANUP=1

%help
	This is an Apptainer container of Ubuntu 22.04 with Matlab runtimes installed on top of the hyakvnc-freesurfer-ubuntu22.04 container.

%setup
	[ -n "${APPTAINER_ROOTFS:-}" ] && ../../bin/write-apptainer-labels.sh > "${APPTAINER_ROOTFS}/.build_labels"

%post
	set -eux
	export DEBIAN_FRONTEND=noninteractive
  APT_CLEANUP="{{APT_CLEANUP}}"

	# Update the package list:
	apt-get update -y -qq

  # Install MCR dependencies:
  apt-get install -y libxt-dev libxext-dev libncurses5

  # Install MCR:
  fs_install_mcr "{{MCR_VERSION}}"

  # Clean up packages:
  [ "${APT_CLEANUP:-0}" = 1 ] && apt-get clean -y -qq && rm -rf /var/lib/apt/lists/*
