Bootstrap: {{BOOTSTRAP_SOURCE}}
From: {{BOOTSTRAP_FROM_REPO}}/{{BOOTSTRAP_FROM_IMAGE}}{{BOOTSTRAP_FROM_SUFFIX}}

%arguments
	BOOTSTRAP_SOURCE=localimage
	BOOTSTRAP_FROM_REPO=../../sif
	BOOTSTRAP_FROM_IMAGE=hyakvnc-vncserver-ubuntu22.04
	BOOTSTRAP_FROM_SUFFIX=.sif
	FREESURFER_VERSION=7.4.1
	FREESURFER_DOWNLOAD_URL=https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/{{FREESURFER_VERSION}}/freesurfer_ubuntu22-{{FREESURFER_VERSION}}_amd64.deb
	FREESURFER_DOWNLOAD_FILENAME=freesurfer_ubuntu22-{{FREESURFER_VERSION}}_amd64.deb
	SETUP_DOWNLOADS_DIR=../../.setup-downloads
	RECON_ALL_CLINICAL_HASH=ecdf46e
	RECON_ALL_CLINICAL_URL=https://raw.githubusercontent.com/freesurfer/freesurfer/{{RECON_ALL_CLINICAL_HASH}}/recon_all_clinical/recon-all-clinical.sh
  MCR_VERSION=R2014b

%help
This is an Apptainer container of Ubuntu 22.04 with FreeSurfer installed. It is designed to be run on the Hyak cluster at the University of Washington with the hyakvnc script.

%setup
	[ -n "${APPTAINER_ROOTFS:-}" ] && ../../bin/write-apptainer-labels.sh > "${APPTAINER_ROOTFS}/.build_labels"
	mkdir -p "{{SETUP_DOWNLOADS_DIR}}"
	if ! [ -r "{{SETUP_DOWNLOADS_DIR}}/{{FREESURFER_DOWNLOAD_FILENAME}}" ]; then
		command -v curl >/dev/null 2>&1 || { echo "warning: curl not found!" >&2; exit 1; }
		curl --fail --fail-early --compressed --location \
			--output "{{SETUP_DOWNLOADS_DIR}}/{{FREESURFER_DOWNLOAD_FILENAME}}" \
			"{{FREESURFER_DOWNLOAD_URL}}" || { echo "warning: curl failed!" >&2; rm -fv "{{SETUP_DOWNLOADS_DIR}}/{{FREESURFER_DOWNLOAD_FILENAME}}" >&2; exit 1; }
		echo "Downloaded \"{{FREESURFER_DOWNLOAD_FILENAME}}\" from \"{{FREESURFER_DOWNLOAD_URL}}\"."
	fi
	ln -v "{{SETUP_DOWNLOADS_DIR}}/{{FREESURFER_DOWNLOAD_FILENAME}}" "${APPTAINER_ROOTFS}/freesurfer.deb" || { echo "warning: ln failed!" >&2; exit 1; }
	
%files
	../../common/configs/freesurfer/start-freeview.sh /usr/local/bin/start-freeview
	../../common/configs/freesurfer/freeview.desktop /usr/share/applications/freeview.desktop

%post
	set -eux
	export DEBIAN_FRONTEND=noninteractive

	# Update the package list:
	apt-get update -y -qq

	# Install FreeSurfer:
	dpkg --install --force-depends /freesurfer.deb && apt-get install --fix-broken --yes --quiet
	unlink /freesurfer.deb

	# Link /usr/local/freesurfer/dev to /usr/local/freesurfer/{{FREESURFER_VERSION}}:
	# (fixes some scripts that expect this)
	ln -s "/usr/local/freesurfer/{{FREESURFER_VERSION}}" /usr/local/freesurfer/dev

	# Patch recon-all-clinical.sh to fix a bug with FREESURFER_HOME location:
	[ -n "{{RECON_ALL_CLINICAL_URL}}" ] && curl --fail --fail-early --compressed --location \
		--output /usr/local/freesurfer/{{FREESURFER_VERSION}}/bin/recon-all-clinical.sh \
		"{{RECON_ALL_CLINICAL_URL}}" || { echo "warning: curl failed!" >&2; exit 1; }
	chmod a+x /usr/local/freesurfer/{{FREESURFER_VERSION}}/bin/recon-all-clinical.sh

	# Install Matlab Compiler Runtime (MCR) if requested:
  if [ -n "{{MCR_VERSION}}" ]; then
    # Install MCR dependencies:
    apt-get install -y libxt-dev libxext-dev libncurses5
    
		# Set the environment variables for fs_install_mcr to work:
		export FREESURFER_HOME="/usr/local/freesurfer/{{FREESURFER_VERSION}}"
		export PATH="${FREESURFER_HOME}/bin:${PATH}"

    # Install MCR:
    fs_install_mcr "{{MCR_VERSION}}"
  fi
	# Clean up packages:
	apt-get clean -y -qq && apt-get -y autoremove && rm -rf /var/lib/apt/lists/*

%environment
	export FREESURFER_HOME="/usr/local/freesurfer/{{FREESURFER_VERSION}}"
	# Settings from SetupFreeSurfer.sh:
	export OS="Linux"
	export FS_OVERRIDE=0
	export FIX_VERTEX_AREA=""
	export FSF_OUTPUT_FORMAT="nii.gz"
	export SUBJECTS_DIR="${FREESURFER_HOME}/subjects"
	export FUNCTIONALS_DIR="${FREESURFER_HOME}/sessions"
	export MNI_DIR="${FREESURFER_HOME}/mni"
	export LOCAL_DIR="${FREESURFER_HOME}/local"
	export MINC_BIN_DIR="${FREESURFER_HOME}/mni/bin"
	export MINC_LIB_DIR="${FREESURFER_HOME}/mni/lib" 
	export MNI_DATAPATH="${FREESURFER_HOME}/mni/data"
	export PERL5LIB="${MINC_LIB_DIR}/perl5/5.8.5"
	export MNI_PERL5LIB="${MINC_LIB_DIR}/perl5/5.8.5"
	export PATH="${FREESURFER_HOME}/bin:${FREESURFER_HOME}/tktools:${MINC_BIN_DIR}:${PATH}"
	export FS_LICENSE="${FS_LICENSE:-${HOME}/${USER}/.freesurfer_license.txt}"

%labels
	edu.uw.hyakvnc.container.resources.recommends.mem 16G
	edu.uw.hyakvnc.container.resources.requires.mem 8G
	edu.uw.hyakvnc.container.resources.recommends.cpus 4
	edu.uw.hyakvnc.container.resources.requires.cpus 1
	edu.uw.hyakvnc.container.resources.suggests.gpus 1
