Bootstrap: docker
From: ubuntu:22.04

%arguments
	# SETUP_DOWNLOADS_MOUNT [optional] [default: "/opt/.setup-downloads"]:
	# The path to the directory where the setup files will be downloaded.
	# This directory should be mounted as a volume in the container.
	SETUP_DOWNLOADS_MOUNT=/opt/.setup-downloads

	# Set FreeSurfer version to download:
	FREESURFER_VERSION=7.4.1

	# Set Matlab Compiler Runtime (MCR) version to download (blank to skip):
	MCR_VERSION=R2014b

	# Apply recon-all-clinical bugfix for 7.4 & 7.4.1?
	APPLY_RECON_CLINICAL_PATH_FIX=1
	# Info: https://surfer.nmr.mgh.harvard.edu/fswiki/recon-all-clinical
	# WARNING: the script in FreeSurfer 7.4 has a small bug when computing the
	#	surface label files at the end of the script.
	# 	Please replace $FREESURFER_HOME/bin/recon-all-clinical.sh with the latest
	#	version HERE. Development versions newer than June 15th 2023 do not have
	#   this problem.

%setup
	# Set the default download directory to cache large downloads:
	[ -n "{{SETUP_DOWNLOADS_MOUNT}}" ] && export DOWNLOAD_DIR="{{SETUP_DOWNLOADS_MOUNT}}" && mkdir -p "${APPTAINER_ROOTFS}/${DOWNLOAD_DIR}"

%help
This is an Apptainer container of Ubuntu 22.04 with FreeSurfer installed.
It is designed to be run on the Hyak cluster at the University of Washington with 
the hyakvnc script.

%labels
	edu.uw.hyakvnc.container.resources.recommends.mem 16G
	edu.uw.hyakvnc.container.resources.requires.mem 8G
	edu.uw.hyakvnc.container.resources.recommends.cpus 4
	edu.uw.hyakvnc.container.resources.requires.cpus 1
	edu.uw.hyakvnc.container.resources.suggests.gpus 1

%files
	../../common /opt/setup

%post
	set -o errexit -o nounset -o xtrace
	[ -n "${DOWNLOAD_DIR:-}" ] && ls -la "${DOWNLOAD_DIR}"

	export DEBIAN_FRONTEND=noninteractive
	apt-get update -y -qq

	. /opt/setup/scripts/setup-ubuntu22.04-hyakvnc-vncserver.sh

	# Install FreeSurfer:
	/opt/setup/scripts/install-freesurfer.sh || { echo "ERROR: install-freesurfer.sh failed!" >&2; exit 1; }

	# Set FREESURFER_HOME:
	FREESURFER_HOME="$(dpkg --listfiles freesurfer | grep --max-count=1 '\/SetUpFreeSurfer\.sh$' | xargs dirname)" || { echo "ERROR: FREESURFER_HOME directory not found!" >&2; exit 1; }
	[ -d "${FREESURFER_HOME}" ] || { echo "ERROR: FREESURFER_HOME directory not found!" >&2; exit 1; }
	export FREESURFER_HOME

	# Patch recon-all-clinical.sh to fix a bug with FREESURFER_HOME location:
	if [ "{{APPLY_RECON_CLINICAL_PATH_FIX}}" = 1 ] && [ -r "${FREESURFER_HOME}/bin/recon-all-clinical.sh" ]; then
		sed -i -E 's/--ctab\s+\/usr\/local\/freesurfer\/dev/--ctab "$FREESURFER_HOME"/g' "${FREESURFER_HOME}/bin/recon-all-clinical.sh"
	fi

	# Install Matlab Compiler Runtime (MCR) if requested:
	if [ -n "{{MCR_VERSION}}" ]; then
		# Install MCR dependencies:
		apt-get install -y libxt-dev libxext-dev libncurses5
		export MCR_VERSION="{{MCR_VERSION}}"
		/opt/setup/scripts/install-fs-mcr.sh || { echo "ERROR: install-fs-mcr.sh failed!" >&2; exit 1; }
	fi

	# Set up the environment by sourcing the FreeSurfer setup script, filtering out the environment variables that are already set in the container, and writing the remaining environment variables to the /.singularity.d/env directory:
	printenv | grep -oE '.*=' | tr -d '=' | sort | uniq >/tmp/current_env_names.txt
	bash -c "source "${FREESURFER_HOME}/SetUpFreeSurfer.sh" && printenv" >/tmp/freesurfer_env.txt
	grep -oE '.*=' /tmp/freesurfer_env.txt | tr -d '=' | sort | uniq >/tmp/freesurfer_env_names.txt
	unique_freesurfer_env_names="$(comm -13 /tmp/current_env_names.txt /tmp/freesurfer_env_names.txt | paste -s -d'|' || true)"

	echo "export FREESURFER_HOME=\"${FREESURFER_HOME}\"" >>/.singularity.d/env/101-hyakvnc-freesurfer-env.sh
	grep -E "^($unique_freesurfer_env_names)=" /tmp/freesurfer_env.txt | sed 's/^/export /g' >>/.singularity.d/env/101-hyakvnc-freesurfer-env.sh
	
	echo "export PATH=\"${FREESURFER_HOME}:\${PATH}\"" >>/.singularity.d/env/101-hyakvnc-freesurfer-env.sh

	# Show the contents of the environment file:
	[ -f "/singularity.d/env/101-hyakvnc-freesurfer-env.sh" ] && echo >&2 "/singularity.d/env/101-hyakvnc-freesurfer-env.sh contents:" && cat "/singularity.d/env/101-hyakvnc-freesurfer-env.sh" >&2

	# Erase the setup files:
	rm -rf /opt/setup

	# Clean up packages:
	apt-get clean -y -qq && apt-get -y autoremove && rm -rf /var/lib/apt/lists/*

%environment
	export SHELL="${SHELL:-/bin/bash}"

%runscript
  hyakvnc-vncserver "$@"

%startscript
  hyakvnc-vncserver "$@"

%apprun vncserver
  hyakvnc-vncserver "$@"

%appstart vncserver
  hyakvnc-vncserver "$@"
