Bootstrap: {{BOOTSTRAP_SOURCE}}
From: {{BOOTSTRAP_FROM_REPO}}/hyakvnc-vncserver-ubuntu22.04{{BOOTSTRAP_FROM_SUFFIX}}

%arguments
	BOOTSTRAP_SOURCE=localimage
	BOOTSTRAP_FROM_REPO=../../sif
	BOOTSTRAP_FROM_SUFFIX=.sif
	FREESURFER_VERSION=7.4.1
	FREESURFER_DOWNLOAD_URL=https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/{{FREESURFER_VERSION}}/freesurfer_ubuntu22-{{FREESURFER_VERSION}}_amd64.deb
	FREESURFER_DOWNLOAD_FILENAME=freesurfer_ubuntu22-{{FREESURFER_VERSION}}_amd64.deb
	SETUP_DOWNLOADS_DIR=../../.setup-downloads

%help
	This is an Apptainer container of Ubuntu 22.04 with TurboVNC, XFCE, and FreeSurfer installed.
	It is designed to be run on the Hyak cluster at the University of Washington with the hyakvnc script.

%setup
	[ -n "${APPTAINER_ROOTFS:-}" ] && ../../bin/write-apptainer-labels.sh > "${APPTAINER_ROOTFS}/.build_labels"
	mkdir -p "{{SETUP_DOWNLOADS_DIR}}"
	if ! [ -r "{{SETUP_DOWNLOADS_DIR}}/{{FREESURFER_DOWNLOAD_FILENAME}}" ]; then
		command -v curl >/dev/null 2>&1 || { echo "warning: curl not found!" >&2; exit 1; }
		curl --fail --fail-early --compressed --location \
			--continue-at - \
			--output "{{SETUP_DOWNLOADS_DIR}}/{{FREESURFER_DOWNLOAD_FILENAME}}" \
			"{{FREESURFER_DOWNLOAD_URL}}" || { echo "warning: curl failed!" >&2; rm -fv "{{SETUP_DOWNLOADS_DIR}}/{{FREESURFER_DOWNLOAD_FILENAME}}" >&2; exit 1; }
		echo "Downloaded \"{{FREESURFER_DOWNLOAD_FILENAME}}\" from \"{{FREESURFER_DOWNLOAD_URL}}\"."
	fi
	ln -v "{{SETUP_DOWNLOADS_DIR}}/{{FREESURFER_DOWNLOAD_FILENAME}}" "${APPTAINER_ROOTFS}/freesurfer.deb" || { echo "warning: ln failed!" >&2; exit 1; }
	

%labels
	org.label-schema.description An Apptainer container of Ubuntu 22.04 with TurboVNC and FreeSurfer installed.
	edu.uw.hyakvnc.container.resources.recommends.mem 16G
	edu.uw.hyakvnc.container.resources.requires.mem 8G
	edu.uw.hyakvnc.container.resources.recommends.cpus 4
	edu.uw.hyakvnc.container.resources.requires.cpus 1
	edu.uw.hyakvnc.container.resources.suggests.gpus 1

%help
	This is an Apptainer container of Ubuntu 22.04 with TurboVNC and FreeSurfer installed.

%files
	../../common/configs/freesurfer/start-freeview.sh /usr/local/bin/start-freeview
	../../common/configs/freesurfer/freeview.desktop /usr/share/applications/freeview.desktop

%environment
	export FREESURFER_HOME="/usr/local/freesurfer/{{FREESURFER_VERSION}}"
	# Settings from SetupFreeSurfer.sh:
	export OS="Linux"
	export FS_OVERRIDE=0
	export FIX_VERTEX_AREA=""
	export FSF_OUTPUT_FORMAT="nii.gz"
	export SUBJECTS_DIR="${FREESURFER_HOME}/subjects"
	export FUNCTIONALS_DIR="${FREESURFER_HOME}/sessions"
	export MNI_DIR="${FREESURFER_HOME}/mni"
	export LOCAL_DIR="${FREESURFER_HOME}/local"
	export MINC_BIN_DIR="${FREESURFER_HOME}/mni/bin"
	export MINC_LIB_DIR="${FREESURFER_HOME}/mni/lib" 
	export MNI_DATAPATH="${FREESURFER_HOME}/mni/data"
	export PERL5LIB="${MINC_LIB_DIR}/perl5/5.8.5"
	export MNI_PERL5LIB="${MINC_LIB_DIR}/perl5/5.8.5"
	export PATH="${FREESURFER_HOME}/bin:${FREESURFER_HOME}/tktools:${MINC_BIN_DIR}:$PATH"
	export FS_LICENSE="${FS_LICENSE:-${HOME}/${USER}/.freesurfer_license.txt}"

%post
	set -eux
	export DEBIAN_FRONTEND=noninteractive

	# Update the package list:
	apt-get update -y -qq

	# Install FreeSurfer:
	dpkg --install --force-depends /freesurfer.deb && apt-get install --fix-broken --yes --quiet
	unlink /freesurfer.deb

	# Clean up packages:
	apt-get clean -y -qq && rm -rf /var/lib/apt/lists/*
